#!/bin/bash
#Created by Kyle Ericson
#Date March 19th 2019

/usr/bin/profiles -I -F /tmp/Jamf-Connect/key.mobileconfig

/usr/bin/profiles -I -F /tmp/Jamf-Connect/jlogin.mobileconfig

/usr/bin/profiles -I -F /tmp/Jamf-Connect/verify.mobileconfig

cp /tmp/Jamf-Connect/com.jamfverify.plist /Library/LaunchAgents/

sudo chown root:wheel /Library/LaunchAgents/com.jamfverify.plist

sudo installer -store -pkg "/tmp/Jamf-Connect/JamfConnectVerify-1.0.0.pkg" -target /

sudo installer -store -pkg "/tmp/Jamf-Connect/JamfConnectLogin-1.0.1.pkg" -target /

exit 0
